spring.application.name=springdemo
spring.datasource.url=jdbc:postgresql://localhost:5432/Assessment
spring.datasource.username=postgres
spring.datasource.password=rrj
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port = 8764